backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - label: Affiliate Links
    name: affiliateLinks
    folder: src/data/affiliate-links
    create: true
    slug: '{{id}}'
    editor:
      preview: false
    fields:
      - label: Data Key
        name: dataKey
        widget: hidden
        default: affiliateLinks
      - label: Id (Should Be Unique & Don't change it)
        name: id
        widget: string
      - label: Link
        name: link
        widget: string
  - label: Articles
    name: article
    folder: src/pages/article
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: article-page
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Tags
        name: tags
        widget: list
        required: false
        fields:
          - label: Name
            name: name
            widget: string
          - label: Image
            name: image
            widget: image
      - label: Article Image
        name: articleImage
        widget: image
        required: false
      - label: Body
        name: body
        widget: markdown
      - label: Related Articles (Maximum 3)
        name: relatedArticles
        widget: list
        max: 3
        required: false
        fields:
          - label: Article
            name: article
            widget: relation
            collection: article
            value_field: slug
            search_fields: [title]
            display_fields: [title]
  - label: Navbar & Footer
    name: data
    editor:
      preview: false
    files:
      - label: Navbar
        name: navbar
        file: src/data/navbar.md
        fields:
          - label: Data Key
            name: dataKey
            widget: hidden
            default: navbar
          - label: Logo
            name: logo
            widget: image
          - label: Menu items
            name: menuitems
            widget: list
            fields:
              - label: Title
                name: title
              - label: Link
                name: link
      - label: Footer
        name: footer
        file: src/data/footer.md
        fields:
          - label: Data Key
            name: dataKey
            widget: hidden
            default: footer
          - label: Column 1
            name: column1
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Social links
                name: socialLinks
                widget: object
                fields:
                  - label: Facebook
                    name: facebook
                    widget: string
                    required: false
                  - label: Youtube
                    name: youtube
                    widget: string
                    required: false
                  - label: Pinterest
                    name: pinterest
                    widget: string
                    required: false
                  - label: Linkedin
                    name: linkedin
                    widget: string
                    required: false
          - label: Column 2
            name: column2
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Links
                name: links
                widget: list
                fields:
                  - label: Title
                    name: title
                  - label: Link
                    name: link
          - label: Column 3
            name: column3
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Links
                name: links
                widget: list
                fields:
                  - label: Title
                    name: title
                  - label: Link
                    name: link
          - label: Column 4
            name: column4
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Button Text
                name: buttonText
                widget: string
              - label: Placeholder Text
                name: placeholderText
                widget: string
  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      - label: Home Page
        name: index
        file: src/pages/index.md
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Tagline
            name: tagline
            widget: string
          - label: Feature tags
            name: featureTags
            widget: object
            fields:
              - label: Item 1
                name: item1
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Link
                    name: link
                    widget: string
              - label: Item 2
                name: item2
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Link
                    name: link
                    widget: string
              - label: Item 3
                name: item3
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Link
                    name: link
                    widget: string
              - label: Item 4
                name: item4
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Link
                    name: link
                    widget: string
          - label: Section 2
            name: section2
            widget: object
            fields:
              - label: Image
                name: image
                widget: image
              - label: Tagline
                name: tagline
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Button Text
                name: buttonText
                widget: string
              - label: Button Link
                name: buttonLink
                widget: string
          - label: Feature Articles
            name: featureArticles
            widget: object
            fields:
              - label: Button Text
                name: buttonText
                widget: string
              - label: Articles
                name: articles
                widget: list
                fields:
                  - label: Article
                    name: article
                    widget: relation
                    collection: article
                    value_field: slug
                    search_fields: [title]
                    display_fields: [title]
          - label: Section 3
            name: section3
            widget: object
            fields:
              - label: Tagline
                name: tagline
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Content List
                name: contentList
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Description
                    name: description
                    widget: text
              - label: Image
                name: image
                widget: image
          - label: Section 4
            name: section4
            widget: object
            fields:
              - label: Tagline
                name: tagline
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Category List
                name: categoryList
                widget: list
                fields:
                  - label: Title
                    name: title
                  - label: Link
                    name: link
      - label: Tags Page
        name: tagsPage
        file: src/data/tags-page.md
        fields:
          - label: Data Key
            name: dataKey
            widget: hidden
            default: tagsPage
          - label: Cover Image
            name: coverImage
            widget: image
          - label: Main Title
            name: mainTitle
            widget: string
          - label: Secondary Title
            name: secondaryTitle
            widget: string
          - label: Recent Article Title
            name: recentArticleTitle
            widget: string
      - label: Single Tag Page
        name: tagPage
        file: src/data/tag-page.md
        fields:
          - label: Data Key
            name: dataKey
            widget: hidden
            default: tagPage
          - label: Cover Image
            name: coverImage
            widget: image
          - label: Main Title
            name: mainTitle
            widget: string
          - label: Secondary Title
            name: secondaryTitle
            widget: string
      - label: Articles Page
        name: articlesPage
        file: src/data/articles-page.md
        fields:
          - label: Data Key
            name: dataKey
            widget: hidden
            default: articlesPage
          - label: Cover Image
            name: coverImage
            widget: image
          - label: Main Title
            name: mainTitle
            widget: string
          - label: Secondary Title
            name: secondaryTitle
            widget: string
      - label: Single Article Page
        name: articlePage
        file: src/data/article-page.md
        fields:
          - label: Data Key
            name: dataKey
            widget: hidden
            default: articlePage
          - label: Related Article Title
            name: relatedArticleTitle
            widget: string
